# INTRODUCTION TO PANDAS

In [121]:
# Install pandas using pip
!pip install pandas

Requirement already satisfied: pandas in /home/mojez-hasan/anaconda3/envs/language_decipher/lib/python3.9/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.22.4 in /home/mojez-hasan/anaconda3/envs/language_decipher/lib/python3.9/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/mojez-hasan/anaconda3/envs/language_decipher/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/mojez-hasan/anaconda3/envs/language_decipher/lib/python3.9/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/mojez-hasan/anaconda3/envs/language_decipher/lib/python3.9/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /home/mojez-hasan/anaconda3/envs/language_decipher/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# Key Data Structures in Pandas
* Series (one dimentional)
* DataFrame (two dimentional)

In [122]:
import pandas as pd
print(pd.__version__)

2.2.3

In [123]:
s = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])

In [124]:
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [125]:
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

In [126]:
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [127]:
df = pd.read_csv("office_employees.csv")

In [128]:
df

,employee_id,name,department,position,salary,date_joined,email
0,EMP001,Gary Harper,Engineering,Frontend Developer,74889,2022-01-30,gary.harper@company.com
1,EMP002,Lee Walsh,IT Support,System Administrator,115131,2022-01-02,lee.walsh@company.com
2,EMP003,John Soto,Human Resources,HR Executive,107183,2019-07-08,john.soto@company.com
3,EMP004,Jennifer Foley,Finance,Financial Analyst,116032,2024-11-21,jennifer.foley@company.com
4,EMP005,Valerie Taylor,Marketing,Content Strategist,85420,2020-04-19,valerie.taylor@company.com
5,EMP006,Alan Phillips,Marketing,Social Media Manager,116912,2024-11-27,alan.phillips@company.com
6,EMP007,Ashley Henderson,Human Resources,HR Executive,85517,2023-01-05,ashley.henderson@company.com
7,EMP008,Raymond Ellis,Finance,Financial Analyst,66548,2021-10-28,raymond.ellis@company.com
8,EMP009,William Baker,Marketing,Content Strategist,85118,2024-05-03,william.baker@company.com
9,EMP010,Justin James,Sales,Sales Associate,72928,2022-06-03,justin.james@company.com
10,EMP011,Nicholas Edwards,Sales,Sales Associate,68327,2024-10-04,nicholas.edwards@company.com
11,EMP012,Matthew Williams,IT Support,System Administrator,71895,2019-12-11,matthew.williams@company.com
12,EMP013,Nathan Carpenter DDS,Engineering,DevOps Engineer,112869,2019-06-14,nathan.carpenter.dds@company.com
13,EMP014,April Gonzalez,Engineering,Backend Developer,93758,2021-04-13,april.gonzalez@company.com
14,EMP015,Cody Yoder,Sales,Sales Manager,106635,2023-01-10,cody.yoder@company.com
15,EMP016,Jonathon Henry,Human Resources,HR Executive,117464,2022-07-13,jonathon.henry@company.com
16,EMP017,Evelyn Bautista,Marketing,Content Strategist,77980,2022-09-17,evelyn.bautista@company.com
17,EMP018,Matthew Pierce,Marketing,Content Strategist,106447,2024-11-30,matthew.pierce@company.com
18,EMP019,Makayla Orozco,Sales,Sales Associate,88630,2022-09-13,makayla.orozco@company.com
19,EMP020,Lindsay Diaz,IT Support,System Administrator,100983,2025-03-17,lindsay.diaz@company.com
20,EMP021,Mr. Luis Williams,Engineering,Backend Developer,76696,2019-09-01,mr..luis.williams@company.com
21,EMP022,Kevin Mclean,Marketing,Content Strategist,90045,2020-09-04,kevin.mclean@company.com
22,EMP023,Tyler Wilson DDS,Finance,Accountant,58365,2023-06-07,tyler.wilson.dds@company.com
23,EMP024,Shannon Smith,Finance,Financial Analyst,106443,2019-09-22,shannon.smith@company.com
24,EMP025,Mark Gonzalez,Finance,Accountant,70423,2022-06-08,mark.gonzalez@company.com
25,EMP026,Daniel Lewis,Marketing,Social Media Manager,100234,2022-01-25,daniel.lewis@company.com
26,EMP027,Stephanie Rose,Marketing,SEO Specialist,72039,2024-09-18,stephanie.rose@company.com
27,EMP028,Alyssa Rodriguez,Engineering,Frontend Developer,73745,2019-08-04,alyssa.rodriguez@company.com
28,EMP029,Mrs. Teresa Lutz DVM,Sales,Account Executive,81028,2020-06-22,mrs..teresa.lutz.dvm@company.com
29,EMP030,Cheryl Peterson,IT Support,System Administrator,82193,2021-03-02,cheryl.peterson@company.com
30,EMP031,Laurie Murray,IT Support,IT Technician,55281,2023-07-12,laurie.murray@company.com
31,EMP032,Sean Andrews,Finance,Financial Analyst,99933,2022-03-17,sean.andrews@company.com
32,EMP033,Anthony Sampson,Finance,Financial Analyst,76170,2023-03-18,anthony.sampson@company.com
33,EMP034,Michael Maldonado,Marketing,SEO Specialist,78888,2020-12-13,michael.maldonado@company.com
34,EMP035,John Jones,IT Support,System Administrator,73699,2022-09-06,john.jones@company.com
35,EMP036,Yesenia Klein,Marketing,Social Media Manager,77463,2021-01-02,yesenia.klein@company.com
36,EMP037,Adam Martinez,Marketing,SEO Specialist,97693,2019-11-14,adam.martinez@company.com
37,EMP038,Kendra Ward,Finance,Financial Analyst,73567,2019-08-21,kendra.ward@company.com
38,EMP039,Dennis Harris,Sales,Sales Manager,66568,2024-05-08,dennis.harris@company.com
39,EMP040,Jennifer Mendez,IT Support,IT Technician,92321,2021-10-05,jennifer.mendez@company.com
40,EMP041,Austin Rose,Marketing,Social Media Manager,83986,2020-10-26,austin.rose@company.com
41,EMP042,Grant Hunter,Human Resources,Recruiter,74028,2024-05-14,grant.hunter@company.com
42,EMP043,Kayla Hinton,Marketing,SEO Specialist,113411,2020-11-16,kayla.hinton@company.com
43,EMP044,Anna Cisneros,Engineering,DevOps Engineer,102598,2019-08-28,anna.cisneros@company.com
44,EMP045,Angela Grant,Human Resources,Recruiter,87220,2020-02-01,angela.grant@company.com
45,EMP046,Jennifer Baker,Sales,Account Executive,73902,2019-09-05,jennifer.baker@company.com
46,EMP047,Sean Fuller,Sales,Sales Associate,58420,2024-01-31,sean.fuller@company.com
47,EMP048,Stephanie Townsend,Human Resources,Recruiter,95307,2019-08-24,stephanie.townsend@company.com
48,EMP049,Grant Parker,Sales,Account Executive,55554,2019-05-23,grant.parker@company.com
49,EMP050,Susan Coleman,Marketing,Content Strategist,87292,2021-12-27,susan.coleman@company.com

In [129]:
df.head()

,employee_id,name,department,position,salary,date_joined,email
0,EMP001,Gary Harper,Engineering,Frontend Developer,74889,2022-01-30,gary.harper@company.com
1,EMP002,Lee Walsh,IT Support,System Administrator,115131,2022-01-02,lee.walsh@company.com
2,EMP003,John Soto,Human Resources,HR Executive,107183,2019-07-08,john.soto@company.com
3,EMP004,Jennifer Foley,Finance,Financial Analyst,116032,2024-11-21,jennifer.foley@company.com
4,EMP005,Valerie Taylor,Marketing,Content Strategist,85420,2020-04-19,valerie.taylor@company.com

In [130]:
df.tail()

,employee_id,name,department,position,salary,date_joined,email
45,EMP046,Jennifer Baker,Sales,Account Executive,73902,2019-09-05,jennifer.baker@company.com
46,EMP047,Sean Fuller,Sales,Sales Associate,58420,2024-01-31,sean.fuller@company.com
47,EMP048,Stephanie Townsend,Human Resources,Recruiter,95307,2019-08-24,stephanie.townsend@company.com
48,EMP049,Grant Parker,Sales,Account Executive,55554,2019-05-23,grant.parker@company.com
49,EMP050,Susan Coleman,Marketing,Content Strategist,87292,2021-12-27,susan.coleman@company.com

In [131]:
df.describe()

              salary
count      50.000000
mean    86103.560000
std     17309.596246
min     55281.000000
25%     73710.500000
50%     84552.000000
75%    100158.750000
max    117464.000000

In [132]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  50 non-null     object
 1   name         50 non-null     object
 2   department   50 non-null     object
 3   position     50 non-null     object
 4   salary       50 non-null     int64
 5   date_joined  50 non-null     object
 6   email        50 non-null     object
dtypes: int64(1), object(6)
memory usage: 2.9+ KB

# Data Selection

In [133]:
df.columns

Index(['employee_id', 'name', 'department', 'position', 'salary',
       'date_joined', 'email'],
      dtype='object')

In [134]:
df['name']

0              Gary Harper
1                Lee Walsh
2                John Soto
3           Jennifer Foley
4           Valerie Taylor
5            Alan Phillips
6         Ashley Henderson
7            Raymond Ellis
8            William Baker
9             Justin James
10        Nicholas Edwards
11        Matthew Williams
12    Nathan Carpenter DDS
13          April Gonzalez
14              Cody Yoder
15          Jonathon Henry
16         Evelyn Bautista
17          Matthew Pierce
18          Makayla Orozco
19            Lindsay Diaz
20       Mr. Luis Williams
21            Kevin Mclean
22        Tyler Wilson DDS
23           Shannon Smith
24           Mark Gonzalez
25            Daniel Lewis
26          Stephanie Rose
27        Alyssa Rodriguez
28    Mrs. Teresa Lutz DVM
29         Cheryl Peterson
30           Laurie Murray
31            Sean Andrews
32         Anthony Sampson
33       Michael Maldonado
34              John Jones
35           Yesenia Klein
36           Adam Martinez
37             Kendra Ward
38           Dennis Harris
39         Jennifer Mendez
40             Austin Rose
41            Grant Hunter
42            Kayla Hinton
43           Anna Cisneros
44            Angela Grant
45          Jennifer Baker
46             Sean Fuller
47      Stephanie Townsend
48            Grant Parker
49           Susan Coleman
Name: name, dtype: object

In [135]:
df[['name','email']]

                    name                             email
0            Gary Harper           gary.harper@company.com
1              Lee Walsh             lee.walsh@company.com
2              John Soto             john.soto@company.com
3         Jennifer Foley        jennifer.foley@company.com
4         Valerie Taylor        valerie.taylor@company.com
5          Alan Phillips         alan.phillips@company.com
6       Ashley Henderson      ashley.henderson@company.com
7          Raymond Ellis         raymond.ellis@company.com
8          William Baker         william.baker@company.com
9           Justin James          justin.james@company.com
10      Nicholas Edwards      nicholas.edwards@company.com
11      Matthew Williams      matthew.williams@company.com
12  Nathan Carpenter DDS  nathan.carpenter.dds@company.com
13        April Gonzalez        april.gonzalez@company.com
14            Cody Yoder            cody.yoder@company.com
15        Jonathon Henry        jonathon.henry@company.com
16       Evelyn Bautista       evelyn.bautista@company.com
17        Matthew Pierce        matthew.pierce@company.com
18        Makayla Orozco        makayla.orozco@company.com
19          Lindsay Diaz          lindsay.diaz@company.com
20     Mr. Luis Williams     mr..luis.williams@company.com
21          Kevin Mclean          kevin.mclean@company.com
22      Tyler Wilson DDS      tyler.wilson.dds@company.com
23         Shannon Smith         shannon.smith@company.com
24         Mark Gonzalez         mark.gonzalez@company.com
25          Daniel Lewis          daniel.lewis@company.com
26        Stephanie Rose        stephanie.rose@company.com
27      Alyssa Rodriguez      alyssa.rodriguez@company.com
28  Mrs. Teresa Lutz DVM  mrs..teresa.lutz.dvm@company.com
29       Cheryl Peterson       cheryl.peterson@company.com
30         Laurie Murray         laurie.murray@company.com
31          Sean Andrews          sean.andrews@company.com
32       Anthony Sampson       anthony.sampson@company.com
33     Michael Maldonado     michael.maldonado@company.com
34            John Jones            john.jones@company.com
35         Yesenia Klein         yesenia.klein@company.com
36         Adam Martinez         adam.martinez@company.com
37           Kendra Ward           kendra.ward@company.com
38         Dennis Harris         dennis.harris@company.com
39       Jennifer Mendez       jennifer.mendez@company.com
40           Austin Rose           austin.rose@company.com
41          Grant Hunter          grant.hunter@company.com
42          Kayla Hinton          kayla.hinton@company.com
43         Anna Cisneros         anna.cisneros@company.com
44          Angela Grant          angela.grant@company.com
45        Jennifer Baker        jennifer.baker@company.com
46           Sean Fuller           sean.fuller@company.com
47    Stephanie Townsend    stephanie.townsend@company.com
48          Grant Parker          grant.parker@company.com
49         Susan Coleman         susan.coleman@company.com

In [136]:
df.iloc[0]

employee_id                     EMP001
name                       Gary Harper
department                 Engineering
position            Frontend Developer
salary                           74889
date_joined                 2022-01-30
email          gary.harper@company.com
Name: 0, dtype: object

In [137]:
df2 = pd.read_csv('missing_office.csv')

In [138]:
df2.head()

,employee_id,name,department,position,salary,date_joined,email
0,EMP001,Gary Harper,Engineering,Frontend Developer,74889.0,2022-01-30,gary.harper@company.com
1,EMP002,Lee Walsh,IT Support,System Administrator,115131.0,2022-01-02,lee.walsh@company.com
2,EMP003,John Soto,Human Resources,NaN,107183.0,2019-07-08,john.soto@company.com
3,EMP004,Jennifer Foley,Finance,Financial Analyst,NaN,2024-11-21,jennifer.foley@company.com
4,EMP005,Valerie Taylor,Marketing,Content Strategist,85420.0,2020-04-19,valerie.taylor@company.com

In [139]:
df2.dropna()

,employee_id,name,department,position,salary,date_joined,email
0,EMP001,Gary Harper,Engineering,Frontend Developer,74889.0,2022-01-30,gary.harper@company.com
1,EMP002,Lee Walsh,IT Support,System Administrator,115131.0,2022-01-02,lee.walsh@company.com
4,EMP005,Valerie Taylor,Marketing,Content Strategist,85420.0,2020-04-19,valerie.taylor@company.com
5,EMP006,Alan Phillips,Marketing,Social Media Manager,116912.0,2024-11-27,alan.phillips@company.com
7,EMP008,Raymond Ellis,Finance,Financial Analyst,66548.0,2021-10-28,raymond.ellis@company.com
8,EMP009,William Baker,Marketing,Content Strategist,85118.0,2024-05-03,william.baker@company.com
9,EMP010,Justin James,Sales,Sales Associate,72928.0,2022-06-03,justin.james@company.com
10,EMP011,Nicholas Edwards,Sales,Sales Associate,68327.0,2024-10-04,nicholas.edwards@company.com
12,EMP013,Nathan Carpenter DDS,Engineering,DevOps Engineer,112869.0,2019-06-14,nathan.carpenter.dds@company.com
13,EMP014,April Gonzalez,Engineering,Backend Developer,93758.0,2021-04-13,april.gonzalez@company.com
14,EMP015,Cody Yoder,Sales,Sales Manager,106635.0,2023-01-10,cody.yoder@company.com
15,EMP016,Jonathon Henry,Human Resources,HR Executive,117464.0,2022-07-13,jonathon.henry@company.com
16,EMP017,Evelyn Bautista,Marketing,Content Strategist,77980.0,2022-09-17,evelyn.bautista@company.com
17,EMP018,Matthew Pierce,Marketing,Content Strategist,106447.0,2024-11-30,matthew.pierce@company.com
18,EMP019,Makayla Orozco,Sales,Sales Associate,88630.0,2022-09-13,makayla.orozco@company.com
19,EMP020,Lindsay Diaz,IT Support,System Administrator,100983.0,2025-03-17,lindsay.diaz@company.com
20,EMP021,Mr. Luis Williams,Engineering,Backend Developer,76696.0,2019-09-01,mr..luis.williams@company.com
22,EMP023,Tyler Wilson DDS,Finance,Accountant,58365.0,2023-06-07,tyler.wilson.dds@company.com
23,EMP024,Shannon Smith,Finance,Financial Analyst,106443.0,2019-09-22,shannon.smith@company.com
24,EMP025,Mark Gonzalez,Finance,Accountant,70423.0,2022-06-08,mark.gonzalez@company.com
25,EMP026,Daniel Lewis,Marketing,Social Media Manager,100234.0,2022-01-25,daniel.lewis@company.com
26,EMP027,Stephanie Rose,Marketing,SEO Specialist,72039.0,2024-09-18,stephanie.rose@company.com
27,EMP028,Alyssa Rodriguez,Engineering,Frontend Developer,73745.0,2019-08-04,alyssa.rodriguez@company.com
29,EMP030,Cheryl Peterson,IT Support,System Administrator,82193.0,2021-03-02,cheryl.peterson@company.com
31,EMP032,Sean Andrews,Finance,Financial Analyst,99933.0,2022-03-17,sean.andrews@company.com
32,EMP033,Anthony Sampson,Finance,Financial Analyst,76170.0,2023-03-18,anthony.sampson@company.com
33,EMP034,Michael Maldonado,Marketing,SEO Specialist,78888.0,2020-12-13,michael.maldonado@company.com
34,EMP035,John Jones,IT Support,System Administrator,73699.0,2022-09-06,john.jones@company.com
35,EMP036,Yesenia Klein,Marketing,Social Media Manager,77463.0,2021-01-02,yesenia.klein@company.com
36,EMP037,Adam Martinez,Marketing,SEO Specialist,97693.0,2019-11-14,adam.martinez@company.com
37,EMP038,Kendra Ward,Finance,Financial Analyst,73567.0,2019-08-21,kendra.ward@company.com
38,EMP039,Dennis Harris,Sales,Sales Manager,66568.0,2024-05-08,dennis.harris@company.com
39,EMP040,Jennifer Mendez,IT Support,IT Technician,92321.0,2021-10-05,jennifer.mendez@company.com
40,EMP041,Austin Rose,Marketing,Social Media Manager,83986.0,2020-10-26,austin.rose@company.com
41,EMP042,Grant Hunter,Human Resources,Recruiter,74028.0,2024-05-14,grant.hunter@company.com
42,EMP043,Kayla Hinton,Marketing,SEO Specialist,113411.0,2020-11-16,kayla.hinton@company.com
43,EMP044,Anna Cisneros,Engineering,DevOps Engineer,102598.0,2019-08-28,anna.cisneros@company.com
44,EMP045,Angela Grant,Human Resources,Recruiter,87220.0,2020-02-01,angela.grant@company.com
45,EMP046,Jennifer Baker,Sales,Account Executive,73902.0,2019-09-05,jennifer.baker@company.com
46,EMP047,Sean Fuller,Sales,Sales Associate,58420.0,2024-01-31,sean.fuller@company.com
47,EMP048,Stephanie Townsend,Human Resources,Recruiter,95307.0,2019-08-24,stephanie.townsend@company.com
48,EMP049,Grant Parker,Sales,Account Executive,55554.0,2019-05-23,grant.parker@company.com
49,EMP050,Susan Coleman,Marketing,Content Strategist,87292.0,2021-12-27,susan.coleman@company.com

In [140]:
df2.fillna(0)
# df2.fillna(0, inplace=True) manupilates the orignal csv (not recommended)

,employee_id,name,department,position,salary,date_joined,email
0,EMP001,Gary Harper,Engineering,Frontend Developer,74889.0,2022-01-30,gary.harper@company.com
1,EMP002,Lee Walsh,IT Support,System Administrator,115131.0,2022-01-02,lee.walsh@company.com
2,EMP003,John Soto,Human Resources,0,107183.0,2019-07-08,john.soto@company.com
3,EMP004,Jennifer Foley,Finance,Financial Analyst,0.0,2024-11-21,jennifer.foley@company.com
4,EMP005,Valerie Taylor,Marketing,Content Strategist,85420.0,2020-04-19,valerie.taylor@company.com
5,EMP006,Alan Phillips,Marketing,Social Media Manager,116912.0,2024-11-27,alan.phillips@company.com
6,EMP007,Ashley Henderson,0,HR Executive,85517.0,2023-01-05,ashley.henderson@company.com
7,EMP008,Raymond Ellis,Finance,Financial Analyst,66548.0,2021-10-28,raymond.ellis@company.com
8,EMP009,William Baker,Marketing,Content Strategist,85118.0,2024-05-03,william.baker@company.com
9,EMP010,Justin James,Sales,Sales Associate,72928.0,2022-06-03,justin.james@company.com
10,EMP011,Nicholas Edwards,Sales,Sales Associate,68327.0,2024-10-04,nicholas.edwards@company.com
11,EMP012,Matthew Williams,IT Support,System Administrator,0.0,2019-12-11,matthew.williams@company.com
12,EMP013,Nathan Carpenter DDS,Engineering,DevOps Engineer,112869.0,2019-06-14,nathan.carpenter.dds@company.com
13,EMP014,April Gonzalez,Engineering,Backend Developer,93758.0,2021-04-13,april.gonzalez@company.com
14,EMP015,Cody Yoder,Sales,Sales Manager,106635.0,2023-01-10,cody.yoder@company.com
15,EMP016,Jonathon Henry,Human Resources,HR Executive,117464.0,2022-07-13,jonathon.henry@company.com
16,EMP017,Evelyn Bautista,Marketing,Content Strategist,77980.0,2022-09-17,evelyn.bautista@company.com
17,EMP018,Matthew Pierce,Marketing,Content Strategist,106447.0,2024-11-30,matthew.pierce@company.com
18,EMP019,Makayla Orozco,Sales,Sales Associate,88630.0,2022-09-13,makayla.orozco@company.com
19,EMP020,Lindsay Diaz,IT Support,System Administrator,100983.0,2025-03-17,lindsay.diaz@company.com
20,EMP021,Mr. Luis Williams,Engineering,Backend Developer,76696.0,2019-09-01,mr..luis.williams@company.com
21,EMP022,Kevin Mclean,Marketing,Content Strategist,0.0,2020-09-04,kevin.mclean@company.com
22,EMP023,Tyler Wilson DDS,Finance,Accountant,58365.0,2023-06-07,tyler.wilson.dds@company.com
23,EMP024,Shannon Smith,Finance,Financial Analyst,106443.0,2019-09-22,shannon.smith@company.com
24,EMP025,Mark Gonzalez,Finance,Accountant,70423.0,2022-06-08,mark.gonzalez@company.com
25,EMP026,Daniel Lewis,Marketing,Social Media Manager,100234.0,2022-01-25,daniel.lewis@company.com
26,EMP027,Stephanie Rose,Marketing,SEO Specialist,72039.0,2024-09-18,stephanie.rose@company.com
27,EMP028,Alyssa Rodriguez,Engineering,Frontend Developer,73745.0,2019-08-04,alyssa.rodriguez@company.com
28,EMP029,Mrs. Teresa Lutz DVM,Sales,Account Executive,0.0,2020-06-22,mrs..teresa.lutz.dvm@company.com
29,EMP030,Cheryl Peterson,IT Support,System Administrator,82193.0,2021-03-02,cheryl.peterson@company.com
30,EMP031,Laurie Murray,IT Support,0,55281.0,2023-07-12,laurie.murray@company.com
31,EMP032,Sean Andrews,Finance,Financial Analyst,99933.0,2022-03-17,sean.andrews@company.com
32,EMP033,Anthony Sampson,Finance,Financial Analyst,76170.0,2023-03-18,anthony.sampson@company.com
33,EMP034,Michael Maldonado,Marketing,SEO Specialist,78888.0,2020-12-13,michael.maldonado@company.com
34,EMP035,John Jones,IT Support,System Administrator,73699.0,2022-09-06,john.jones@company.com
35,EMP036,Yesenia Klein,Marketing,Social Media Manager,77463.0,2021-01-02,yesenia.klein@company.com
36,EMP037,Adam Martinez,Marketing,SEO Specialist,97693.0,2019-11-14,adam.martinez@company.com
37,EMP038,Kendra Ward,Finance,Financial Analyst,73567.0,2019-08-21,kendra.ward@company.com
38,EMP039,Dennis Harris,Sales,Sales Manager,66568.0,2024-05-08,dennis.harris@company.com
39,EMP040,Jennifer Mendez,IT Support,IT Technician,92321.0,2021-10-05,jennifer.mendez@company.com
40,EMP041,Austin Rose,Marketing,Social Media Manager,83986.0,2020-10-26,austin.rose@company.com
41,EMP042,Grant Hunter,Human Resources,Recruiter,74028.0,2024-05-14,grant.hunter@company.com
42,EMP043,Kayla Hinton,Marketing,SEO Specialist,113411.0,2020-11-16,kayla.hinton@company.com
43,EMP044,Anna Cisneros,Engineering,DevOps Engineer,102598.0,2019-08-28,anna.cisneros@company.com
44,EMP045,Angela Grant,Human Resources,Recruiter,87220.0,2020-02-01,angela.grant@company.com
45,EMP046,Jennifer Baker,Sales,Account Executive,73902.0,2019-09-05,jennifer.baker@company.com
46,EMP047,Sean Fuller,Sales,Sales Associate,58420.0,2024-01-31,sean.fuller@company.com
47,EMP048,Stephanie Townsend,Human Resources,Recruiter,95307.0,2019-08-24,stephanie.townsend@company.com
48,EMP049,Grant Parker,Sales,Account Executive,55554.0,2019-05-23,grant.parker@company.com
49,EMP050,Susan Coleman,Marketing,Content Strategist,87292.0,2021-12-27,susan.coleman@company.com

In [141]:
df

,employee_id,name,department,position,salary,date_joined,email
0,EMP001,Gary Harper,Engineering,Frontend Developer,74889,2022-01-30,gary.harper@company.com
1,EMP002,Lee Walsh,IT Support,System Administrator,115131,2022-01-02,lee.walsh@company.com
2,EMP003,John Soto,Human Resources,HR Executive,107183,2019-07-08,john.soto@company.com
3,EMP004,Jennifer Foley,Finance,Financial Analyst,116032,2024-11-21,jennifer.foley@company.com
4,EMP005,Valerie Taylor,Marketing,Content Strategist,85420,2020-04-19,valerie.taylor@company.com
5,EMP006,Alan Phillips,Marketing,Social Media Manager,116912,2024-11-27,alan.phillips@company.com
6,EMP007,Ashley Henderson,Human Resources,HR Executive,85517,2023-01-05,ashley.henderson@company.com
7,EMP008,Raymond Ellis,Finance,Financial Analyst,66548,2021-10-28,raymond.ellis@company.com
8,EMP009,William Baker,Marketing,Content Strategist,85118,2024-05-03,william.baker@company.com
9,EMP010,Justin James,Sales,Sales Associate,72928,2022-06-03,justin.james@company.com
10,EMP011,Nicholas Edwards,Sales,Sales Associate,68327,2024-10-04,nicholas.edwards@company.com
11,EMP012,Matthew Williams,IT Support,System Administrator,71895,2019-12-11,matthew.williams@company.com
12,EMP013,Nathan Carpenter DDS,Engineering,DevOps Engineer,112869,2019-06-14,nathan.carpenter.dds@company.com
13,EMP014,April Gonzalez,Engineering,Backend Developer,93758,2021-04-13,april.gonzalez@company.com
14,EMP015,Cody Yoder,Sales,Sales Manager,106635,2023-01-10,cody.yoder@company.com
15,EMP016,Jonathon Henry,Human Resources,HR Executive,117464,2022-07-13,jonathon.henry@company.com
16,EMP017,Evelyn Bautista,Marketing,Content Strategist,77980,2022-09-17,evelyn.bautista@company.com
17,EMP018,Matthew Pierce,Marketing,Content Strategist,106447,2024-11-30,matthew.pierce@company.com
18,EMP019,Makayla Orozco,Sales,Sales Associate,88630,2022-09-13,makayla.orozco@company.com
19,EMP020,Lindsay Diaz,IT Support,System Administrator,100983,2025-03-17,lindsay.diaz@company.com
20,EMP021,Mr. Luis Williams,Engineering,Backend Developer,76696,2019-09-01,mr..luis.williams@company.com
21,EMP022,Kevin Mclean,Marketing,Content Strategist,90045,2020-09-04,kevin.mclean@company.com
22,EMP023,Tyler Wilson DDS,Finance,Accountant,58365,2023-06-07,tyler.wilson.dds@company.com
23,EMP024,Shannon Smith,Finance,Financial Analyst,106443,2019-09-22,shannon.smith@company.com
24,EMP025,Mark Gonzalez,Finance,Accountant,70423,2022-06-08,mark.gonzalez@company.com
25,EMP026,Daniel Lewis,Marketing,Social Media Manager,100234,2022-01-25,daniel.lewis@company.com
26,EMP027,Stephanie Rose,Marketing,SEO Specialist,72039,2024-09-18,stephanie.rose@company.com
27,EMP028,Alyssa Rodriguez,Engineering,Frontend Developer,73745,2019-08-04,alyssa.rodriguez@company.com
28,EMP029,Mrs. Teresa Lutz DVM,Sales,Account Executive,81028,2020-06-22,mrs..teresa.lutz.dvm@company.com
29,EMP030,Cheryl Peterson,IT Support,System Administrator,82193,2021-03-02,cheryl.peterson@company.com
30,EMP031,Laurie Murray,IT Support,IT Technician,55281,2023-07-12,laurie.murray@company.com
31,EMP032,Sean Andrews,Finance,Financial Analyst,99933,2022-03-17,sean.andrews@company.com
32,EMP033,Anthony Sampson,Finance,Financial Analyst,76170,2023-03-18,anthony.sampson@company.com
33,EMP034,Michael Maldonado,Marketing,SEO Specialist,78888,2020-12-13,michael.maldonado@company.com
34,EMP035,John Jones,IT Support,System Administrator,73699,2022-09-06,john.jones@company.com
35,EMP036,Yesenia Klein,Marketing,Social Media Manager,77463,2021-01-02,yesenia.klein@company.com
36,EMP037,Adam Martinez,Marketing,SEO Specialist,97693,2019-11-14,adam.martinez@company.com
37,EMP038,Kendra Ward,Finance,Financial Analyst,73567,2019-08-21,kendra.ward@company.com
38,EMP039,Dennis Harris,Sales,Sales Manager,66568,2024-05-08,dennis.harris@company.com
39,EMP040,Jennifer Mendez,IT Support,IT Technician,92321,2021-10-05,jennifer.mendez@company.com
40,EMP041,Austin Rose,Marketing,Social Media Manager,83986,2020-10-26,austin.rose@company.com
41,EMP042,Grant Hunter,Human Resources,Recruiter,74028,2024-05-14,grant.hunter@company.com
42,EMP043,Kayla Hinton,Marketing,SEO Specialist,113411,2020-11-16,kayla.hinton@company.com
43,EMP044,Anna Cisneros,Engineering,DevOps Engineer,102598,2019-08-28,anna.cisneros@company.com
44,EMP045,Angela Grant,Human Resources,Recruiter,87220,2020-02-01,angela.grant@company.com
45,EMP046,Jennifer Baker,Sales,Account Executive,73902,2019-09-05,jennifer.baker@company.com
46,EMP047,Sean Fuller,Sales,Sales Associate,58420,2024-01-31,sean.fuller@company.com
47,EMP048,Stephanie Townsend,Human Resources,Recruiter,95307,2019-08-24,stephanie.townsend@company.com
48,EMP049,Grant Parker,Sales,Account Executive,55554,2019-05-23,grant.parker@company.com
49,EMP050,Susan Coleman,Marketing,Content Strategist,87292,2021-12-27,susan.coleman@company.com

In [142]:
df.rename(columns={"employee_id": "e_id"})

,e_id,name,department,position,salary,date_joined,email
0,EMP001,Gary Harper,Engineering,Frontend Developer,74889,2022-01-30,gary.harper@company.com
1,EMP002,Lee Walsh,IT Support,System Administrator,115131,2022-01-02,lee.walsh@company.com
2,EMP003,John Soto,Human Resources,HR Executive,107183,2019-07-08,john.soto@company.com
3,EMP004,Jennifer Foley,Finance,Financial Analyst,116032,2024-11-21,jennifer.foley@company.com
4,EMP005,Valerie Taylor,Marketing,Content Strategist,85420,2020-04-19,valerie.taylor@company.com
5,EMP006,Alan Phillips,Marketing,Social Media Manager,116912,2024-11-27,alan.phillips@company.com
6,EMP007,Ashley Henderson,Human Resources,HR Executive,85517,2023-01-05,ashley.henderson@company.com
7,EMP008,Raymond Ellis,Finance,Financial Analyst,66548,2021-10-28,raymond.ellis@company.com
8,EMP009,William Baker,Marketing,Content Strategist,85118,2024-05-03,william.baker@company.com
9,EMP010,Justin James,Sales,Sales Associate,72928,2022-06-03,justin.james@company.com
10,EMP011,Nicholas Edwards,Sales,Sales Associate,68327,2024-10-04,nicholas.edwards@company.com
11,EMP012,Matthew Williams,IT Support,System Administrator,71895,2019-12-11,matthew.williams@company.com
12,EMP013,Nathan Carpenter DDS,Engineering,DevOps Engineer,112869,2019-06-14,nathan.carpenter.dds@company.com
13,EMP014,April Gonzalez,Engineering,Backend Developer,93758,2021-04-13,april.gonzalez@company.com
14,EMP015,Cody Yoder,Sales,Sales Manager,106635,2023-01-10,cody.yoder@company.com
15,EMP016,Jonathon Henry,Human Resources,HR Executive,117464,2022-07-13,jonathon.henry@company.com
16,EMP017,Evelyn Bautista,Marketing,Content Strategist,77980,2022-09-17,evelyn.bautista@company.com
17,EMP018,Matthew Pierce,Marketing,Content Strategist,106447,2024-11-30,matthew.pierce@company.com
18,EMP019,Makayla Orozco,Sales,Sales Associate,88630,2022-09-13,makayla.orozco@company.com
19,EMP020,Lindsay Diaz,IT Support,System Administrator,100983,2025-03-17,lindsay.diaz@company.com
20,EMP021,Mr. Luis Williams,Engineering,Backend Developer,76696,2019-09-01,mr..luis.williams@company.com
21,EMP022,Kevin Mclean,Marketing,Content Strategist,90045,2020-09-04,kevin.mclean@company.com
22,EMP023,Tyler Wilson DDS,Finance,Accountant,58365,2023-06-07,tyler.wilson.dds@company.com
23,EMP024,Shannon Smith,Finance,Financial Analyst,106443,2019-09-22,shannon.smith@company.com
24,EMP025,Mark Gonzalez,Finance,Accountant,70423,2022-06-08,mark.gonzalez@company.com
25,EMP026,Daniel Lewis,Marketing,Social Media Manager,100234,2022-01-25,daniel.lewis@company.com
26,EMP027,Stephanie Rose,Marketing,SEO Specialist,72039,2024-09-18,stephanie.rose@company.com
27,EMP028,Alyssa Rodriguez,Engineering,Frontend Developer,73745,2019-08-04,alyssa.rodriguez@company.com
28,EMP029,Mrs. Teresa Lutz DVM,Sales,Account Executive,81028,2020-06-22,mrs..teresa.lutz.dvm@company.com
29,EMP030,Cheryl Peterson,IT Support,System Administrator,82193,2021-03-02,cheryl.peterson@company.com
30,EMP031,Laurie Murray,IT Support,IT Technician,55281,2023-07-12,laurie.murray@company.com
31,EMP032,Sean Andrews,Finance,Financial Analyst,99933,2022-03-17,sean.andrews@company.com
32,EMP033,Anthony Sampson,Finance,Financial Analyst,76170,2023-03-18,anthony.sampson@company.com
33,EMP034,Michael Maldonado,Marketing,SEO Specialist,78888,2020-12-13,michael.maldonado@company.com
34,EMP035,John Jones,IT Support,System Administrator,73699,2022-09-06,john.jones@company.com
35,EMP036,Yesenia Klein,Marketing,Social Media Manager,77463,2021-01-02,yesenia.klein@company.com
36,EMP037,Adam Martinez,Marketing,SEO Specialist,97693,2019-11-14,adam.martinez@company.com
37,EMP038,Kendra Ward,Finance,Financial Analyst,73567,2019-08-21,kendra.ward@company.com
38,EMP039,Dennis Harris,Sales,Sales Manager,66568,2024-05-08,dennis.harris@company.com
39,EMP040,Jennifer Mendez,IT Support,IT Technician,92321,2021-10-05,jennifer.mendez@company.com
40,EMP041,Austin Rose,Marketing,Social Media Manager,83986,2020-10-26,austin.rose@company.com
41,EMP042,Grant Hunter,Human Resources,Recruiter,74028,2024-05-14,grant.hunter@company.com
42,EMP043,Kayla Hinton,Marketing,SEO Specialist,113411,2020-11-16,kayla.hinton@company.com
43,EMP044,Anna Cisneros,Engineering,DevOps Engineer,102598,2019-08-28,anna.cisneros@company.com
44,EMP045,Angela Grant,Human Resources,Recruiter,87220,2020-02-01,angela.grant@company.com
45,EMP046,Jennifer Baker,Sales,Account Executive,73902,2019-09-05,jennifer.baker@company.com
46,EMP047,Sean Fuller,Sales,Sales Associate,58420,2024-01-31,sean.fuller@company.com
47,EMP048,Stephanie Townsend,Human Resources,Recruiter,95307,2019-08-24,stephanie.townsend@company.com
48,EMP049,Grant Parker,Sales,Account Executive,55554,2019-05-23,grant.parker@company.com
49,EMP050,Susan Coleman,Marketing,Content Strategist,87292,2021-12-27,susan.coleman@company.com

In [143]:
# permanantly rename the column
df.rename(columns={"employee_id": "e_id"}, inplace=True)

In [144]:
df

,e_id,name,department,position,salary,date_joined,email
0,EMP001,Gary Harper,Engineering,Frontend Developer,74889,2022-01-30,gary.harper@company.com
1,EMP002,Lee Walsh,IT Support,System Administrator,115131,2022-01-02,lee.walsh@company.com
2,EMP003,John Soto,Human Resources,HR Executive,107183,2019-07-08,john.soto@company.com
3,EMP004,Jennifer Foley,Finance,Financial Analyst,116032,2024-11-21,jennifer.foley@company.com
4,EMP005,Valerie Taylor,Marketing,Content Strategist,85420,2020-04-19,valerie.taylor@company.com
5,EMP006,Alan Phillips,Marketing,Social Media Manager,116912,2024-11-27,alan.phillips@company.com
6,EMP007,Ashley Henderson,Human Resources,HR Executive,85517,2023-01-05,ashley.henderson@company.com
7,EMP008,Raymond Ellis,Finance,Financial Analyst,66548,2021-10-28,raymond.ellis@company.com
8,EMP009,William Baker,Marketing,Content Strategist,85118,2024-05-03,william.baker@company.com
9,EMP010,Justin James,Sales,Sales Associate,72928,2022-06-03,justin.james@company.com
10,EMP011,Nicholas Edwards,Sales,Sales Associate,68327,2024-10-04,nicholas.edwards@company.com
11,EMP012,Matthew Williams,IT Support,System Administrator,71895,2019-12-11,matthew.williams@company.com
12,EMP013,Nathan Carpenter DDS,Engineering,DevOps Engineer,112869,2019-06-14,nathan.carpenter.dds@company.com
13,EMP014,April Gonzalez,Engineering,Backend Developer,93758,2021-04-13,april.gonzalez@company.com
14,EMP015,Cody Yoder,Sales,Sales Manager,106635,2023-01-10,cody.yoder@company.com
15,EMP016,Jonathon Henry,Human Resources,HR Executive,117464,2022-07-13,jonathon.henry@company.com
16,EMP017,Evelyn Bautista,Marketing,Content Strategist,77980,2022-09-17,evelyn.bautista@company.com
17,EMP018,Matthew Pierce,Marketing,Content Strategist,106447,2024-11-30,matthew.pierce@company.com
18,EMP019,Makayla Orozco,Sales,Sales Associate,88630,2022-09-13,makayla.orozco@company.com
19,EMP020,Lindsay Diaz,IT Support,System Administrator,100983,2025-03-17,lindsay.diaz@company.com
20,EMP021,Mr. Luis Williams,Engineering,Backend Developer,76696,2019-09-01,mr..luis.williams@company.com
21,EMP022,Kevin Mclean,Marketing,Content Strategist,90045,2020-09-04,kevin.mclean@company.com
22,EMP023,Tyler Wilson DDS,Finance,Accountant,58365,2023-06-07,tyler.wilson.dds@company.com
23,EMP024,Shannon Smith,Finance,Financial Analyst,106443,2019-09-22,shannon.smith@company.com
24,EMP025,Mark Gonzalez,Finance,Accountant,70423,2022-06-08,mark.gonzalez@company.com
25,EMP026,Daniel Lewis,Marketing,Social Media Manager,100234,2022-01-25,daniel.lewis@company.com
26,EMP027,Stephanie Rose,Marketing,SEO Specialist,72039,2024-09-18,stephanie.rose@company.com
27,EMP028,Alyssa Rodriguez,Engineering,Frontend Developer,73745,2019-08-04,alyssa.rodriguez@company.com
28,EMP029,Mrs. Teresa Lutz DVM,Sales,Account Executive,81028,2020-06-22,mrs..teresa.lutz.dvm@company.com
29,EMP030,Cheryl Peterson,IT Support,System Administrator,82193,2021-03-02,cheryl.peterson@company.com
30,EMP031,Laurie Murray,IT Support,IT Technician,55281,2023-07-12,laurie.murray@company.com
31,EMP032,Sean Andrews,Finance,Financial Analyst,99933,2022-03-17,sean.andrews@company.com
32,EMP033,Anthony Sampson,Finance,Financial Analyst,76170,2023-03-18,anthony.sampson@company.com
33,EMP034,Michael Maldonado,Marketing,SEO Specialist,78888,2020-12-13,michael.maldonado@company.com
34,EMP035,John Jones,IT Support,System Administrator,73699,2022-09-06,john.jones@company.com
35,EMP036,Yesenia Klein,Marketing,Social Media Manager,77463,2021-01-02,yesenia.klein@company.com
36,EMP037,Adam Martinez,Marketing,SEO Specialist,97693,2019-11-14,adam.martinez@company.com
37,EMP038,Kendra Ward,Finance,Financial Analyst,73567,2019-08-21,kendra.ward@company.com
38,EMP039,Dennis Harris,Sales,Sales Manager,66568,2024-05-08,dennis.harris@company.com
39,EMP040,Jennifer Mendez,IT Support,IT Technician,92321,2021-10-05,jennifer.mendez@company.com
40,EMP041,Austin Rose,Marketing,Social Media Manager,83986,2020-10-26,austin.rose@company.com
41,EMP042,Grant Hunter,Human Resources,Recruiter,74028,2024-05-14,grant.hunter@company.com
42,EMP043,Kayla Hinton,Marketing,SEO Specialist,113411,2020-11-16,kayla.hinton@company.com
43,EMP044,Anna Cisneros,Engineering,DevOps Engineer,102598,2019-08-28,anna.cisneros@company.com
44,EMP045,Angela Grant,Human Resources,Recruiter,87220,2020-02-01,angela.grant@company.com
45,EMP046,Jennifer Baker,Sales,Account Executive,73902,2019-09-05,jennifer.baker@company.com
46,EMP047,Sean Fuller,Sales,Sales Associate,58420,2024-01-31,sean.fuller@company.com
47,EMP048,Stephanie Townsend,Human Resources,Recruiter,95307,2019-08-24,stephanie.townsend@company.com
48,EMP049,Grant Parker,Sales,Account Executive,55554,2019-05-23,grant.parker@company.com
49,EMP050,Susan Coleman,Marketing,Content Strategist,87292,2021-12-27,susan.coleman@company.com

In [145]:
df.describe()

              salary
count      50.000000
mean    86103.560000
std     17309.596246
min     55281.000000
25%     73710.500000
50%     84552.000000
75%    100158.750000
max    117464.000000

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   e_id         50 non-null     object
 1   name         50 non-null     object
 2   department   50 non-null     object
 3   position     50 non-null     object
 4   salary       50 non-null     int64
 5   date_joined  50 non-null     object
 6   email        50 non-null     object
dtypes: int64(1), object(6)
memory usage: 2.9+ KB

In [147]:
# change the data type of a column
df['salary'] = df['salary'].astype(int)
df['salary'].dtype

dtype('int64')

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   e_id         50 non-null     object
 1   name         50 non-null     object
 2   department   50 non-null     object
 3   position     50 non-null     object
 4   salary       50 non-null     int64
 5   date_joined  50 non-null     object
 6   email        50 non-null     object
dtypes: int64(1), object(6)
memory usage: 2.9+ KB

In [149]:
df['e_id'] = df['e_id'].astype("string")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   e_id         50 non-null     string
 1   name         50 non-null     object
 2   department   50 non-null     object
 3   position     50 non-null     object
 4   salary       50 non-null     int64
 5   date_joined  50 non-null     object
 6   email        50 non-null     object
dtypes: int64(1), object(5), string(1)
memory usage: 2.9+ KB

In [150]:
df['zeros'] = [0 for i in range (len(df))]

In [151]:
df

,e_id,name,department,position,salary,date_joined,email,zeros
0,EMP001,Gary Harper,Engineering,Frontend Developer,74889,2022-01-30,gary.harper@company.com,0
1,EMP002,Lee Walsh,IT Support,System Administrator,115131,2022-01-02,lee.walsh@company.com,0
2,EMP003,John Soto,Human Resources,HR Executive,107183,2019-07-08,john.soto@company.com,0
3,EMP004,Jennifer Foley,Finance,Financial Analyst,116032,2024-11-21,jennifer.foley@company.com,0
4,EMP005,Valerie Taylor,Marketing,Content Strategist,85420,2020-04-19,valerie.taylor@company.com,0
5,EMP006,Alan Phillips,Marketing,Social Media Manager,116912,2024-11-27,alan.phillips@company.com,0
6,EMP007,Ashley Henderson,Human Resources,HR Executive,85517,2023-01-05,ashley.henderson@company.com,0
7,EMP008,Raymond Ellis,Finance,Financial Analyst,66548,2021-10-28,raymond.ellis@company.com,0
8,EMP009,William Baker,Marketing,Content Strategist,85118,2024-05-03,william.baker@company.com,0
9,EMP010,Justin James,Sales,Sales Associate,72928,2022-06-03,justin.james@company.com,0
10,EMP011,Nicholas Edwards,Sales,Sales Associate,68327,2024-10-04,nicholas.edwards@company.com,0
11,EMP012,Matthew Williams,IT Support,System Administrator,71895,2019-12-11,matthew.williams@company.com,0
12,EMP013,Nathan Carpenter DDS,Engineering,DevOps Engineer,112869,2019-06-14,nathan.carpenter.dds@company.com,0
13,EMP014,April Gonzalez,Engineering,Backend Developer,93758,2021-04-13,april.gonzalez@company.com,0
14,EMP015,Cody Yoder,Sales,Sales Manager,106635,2023-01-10,cody.yoder@company.com,0
15,EMP016,Jonathon Henry,Human Resources,HR Executive,117464,2022-07-13,jonathon.henry@company.com,0
16,EMP017,Evelyn Bautista,Marketing,Content Strategist,77980,2022-09-17,evelyn.bautista@company.com,0
17,EMP018,Matthew Pierce,Marketing,Content Strategist,106447,2024-11-30,matthew.pierce@company.com,0
18,EMP019,Makayla Orozco,Sales,Sales Associate,88630,2022-09-13,makayla.orozco@company.com,0
19,EMP020,Lindsay Diaz,IT Support,System Administrator,100983,2025-03-17,lindsay.diaz@company.com,0
20,EMP021,Mr. Luis Williams,Engineering,Backend Developer,76696,2019-09-01,mr..luis.williams@company.com,0
21,EMP022,Kevin Mclean,Marketing,Content Strategist,90045,2020-09-04,kevin.mclean@company.com,0
22,EMP023,Tyler Wilson DDS,Finance,Accountant,58365,2023-06-07,tyler.wilson.dds@company.com,0
23,EMP024,Shannon Smith,Finance,Financial Analyst,106443,2019-09-22,shannon.smith@company.com,0
24,EMP025,Mark Gonzalez,Finance,Accountant,70423,2022-06-08,mark.gonzalez@company.com,0
25,EMP026,Daniel Lewis,Marketing,Social Media Manager,100234,2022-01-25,daniel.lewis@company.com,0
26,EMP027,Stephanie Rose,Marketing,SEO Specialist,72039,2024-09-18,stephanie.rose@company.com,0
27,EMP028,Alyssa Rodriguez,Engineering,Frontend Developer,73745,2019-08-04,alyssa.rodriguez@company.com,0
28,EMP029,Mrs. Teresa Lutz DVM,Sales,Account Executive,81028,2020-06-22,mrs..teresa.lutz.dvm@company.com,0
29,EMP030,Cheryl Peterson,IT Support,System Administrator,82193,2021-03-02,cheryl.peterson@company.com,0
30,EMP031,Laurie Murray,IT Support,IT Technician,55281,2023-07-12,laurie.murray@company.com,0
31,EMP032,Sean Andrews,Finance,Financial Analyst,99933,2022-03-17,sean.andrews@company.com,0
32,EMP033,Anthony Sampson,Finance,Financial Analyst,76170,2023-03-18,anthony.sampson@company.com,0
33,EMP034,Michael Maldonado,Marketing,SEO Specialist,78888,2020-12-13,michael.maldonado@company.com,0
34,EMP035,John Jones,IT Support,System Administrator,73699,2022-09-06,john.jones@company.com,0
35,EMP036,Yesenia Klein,Marketing,Social Media Manager,77463,2021-01-02,yesenia.klein@company.com,0
36,EMP037,Adam Martinez,Marketing,SEO Specialist,97693,2019-11-14,adam.martinez@company.com,0
37,EMP038,Kendra Ward,Finance,Financial Analyst,73567,2019-08-21,kendra.ward@company.com,0
38,EMP039,Dennis Harris,Sales,Sales Manager,66568,2024-05-08,dennis.harris@company.com,0
39,EMP040,Jennifer Mendez,IT Support,IT Technician,92321,2021-10-05,jennifer.mendez@company.com,0
40,EMP041,Austin Rose,Marketing,Social Media Manager,83986,2020-10-26,austin.rose@company.com,0
41,EMP042,Grant Hunter,Human Resources,Recruiter,74028,2024-05-14,grant.hunter@company.com,0
42,EMP043,Kayla Hinton,Marketing,SEO Specialist,113411,2020-11-16,kayla.hinton@company.com,0
43,EMP044,Anna Cisneros,Engineering,DevOps Engineer,102598,2019-08-28,anna.cisneros@company.com,0
44,EMP045,Angela Grant,Human Resources,Recruiter,87220,2020-02-01,angela.grant@company.com,0
45,EMP046,Jennifer Baker,Sales,Account Executive,73902,2019-09-05,jennifer.baker@company.com,0
46,EMP047,Sean Fuller,Sales,Sales Associate,58420,2024-01-31,sean.fuller@company.com,0
47,EMP048,Stephanie Townsend,Human Resources,Recruiter,95307,2019-08-24,stephanie.townsend@company.com,0
48,EMP049,Grant Parker,Sales,Account Executive,55554,2019-05-23,grant.parker@company.com,0
49,EMP050,Susan Coleman,Marketing,Content Strategist,87292,2021-12-27,susan.coleman@company.com,0

In [152]:
def fx(a):
    return a + 1
df['zeros + 1'] = df['zeros'].apply(fx)

In [153]:
df

,e_id,name,department,position,salary,date_joined,email,zeros,zeros + 1
0,EMP001,Gary Harper,Engineering,Frontend Developer,74889,2022-01-30,gary.harper@company.com,0,1
1,EMP002,Lee Walsh,IT Support,System Administrator,115131,2022-01-02,lee.walsh@company.com,0,1
2,EMP003,John Soto,Human Resources,HR Executive,107183,2019-07-08,john.soto@company.com,0,1
3,EMP004,Jennifer Foley,Finance,Financial Analyst,116032,2024-11-21,jennifer.foley@company.com,0,1
4,EMP005,Valerie Taylor,Marketing,Content Strategist,85420,2020-04-19,valerie.taylor@company.com,0,1
5,EMP006,Alan Phillips,Marketing,Social Media Manager,116912,2024-11-27,alan.phillips@company.com,0,1
6,EMP007,Ashley Henderson,Human Resources,HR Executive,85517,2023-01-05,ashley.henderson@company.com,0,1
7,EMP008,Raymond Ellis,Finance,Financial Analyst,66548,2021-10-28,raymond.ellis@company.com,0,1
8,EMP009,William Baker,Marketing,Content Strategist,85118,2024-05-03,william.baker@company.com,0,1
9,EMP010,Justin James,Sales,Sales Associate,72928,2022-06-03,justin.james@company.com,0,1
10,EMP011,Nicholas Edwards,Sales,Sales Associate,68327,2024-10-04,nicholas.edwards@company.com,0,1
11,EMP012,Matthew Williams,IT Support,System Administrator,71895,2019-12-11,matthew.williams@company.com,0,1
12,EMP013,Nathan Carpenter DDS,Engineering,DevOps Engineer,112869,2019-06-14,nathan.carpenter.dds@company.com,0,1
13,EMP014,April Gonzalez,Engineering,Backend Developer,93758,2021-04-13,april.gonzalez@company.com,0,1
14,EMP015,Cody Yoder,Sales,Sales Manager,106635,2023-01-10,cody.yoder@company.com,0,1
15,EMP016,Jonathon Henry,Human Resources,HR Executive,117464,2022-07-13,jonathon.henry@company.com,0,1
16,EMP017,Evelyn Bautista,Marketing,Content Strategist,77980,2022-09-17,evelyn.bautista@company.com,0,1
17,EMP018,Matthew Pierce,Marketing,Content Strategist,106447,2024-11-30,matthew.pierce@company.com,0,1
18,EMP019,Makayla Orozco,Sales,Sales Associate,88630,2022-09-13,makayla.orozco@company.com,0,1
19,EMP020,Lindsay Diaz,IT Support,System Administrator,100983,2025-03-17,lindsay.diaz@company.com,0,1
20,EMP021,Mr. Luis Williams,Engineering,Backend Developer,76696,2019-09-01,mr..luis.williams@company.com,0,1
21,EMP022,Kevin Mclean,Marketing,Content Strategist,90045,2020-09-04,kevin.mclean@company.com,0,1
22,EMP023,Tyler Wilson DDS,Finance,Accountant,58365,2023-06-07,tyler.wilson.dds@company.com,0,1
23,EMP024,Shannon Smith,Finance,Financial Analyst,106443,2019-09-22,shannon.smith@company.com,0,1
24,EMP025,Mark Gonzalez,Finance,Accountant,70423,2022-06-08,mark.gonzalez@company.com,0,1
25,EMP026,Daniel Lewis,Marketing,Social Media Manager,100234,2022-01-25,daniel.lewis@company.com,0,1
26,EMP027,Stephanie Rose,Marketing,SEO Specialist,72039,2024-09-18,stephanie.rose@company.com,0,1
27,EMP028,Alyssa Rodriguez,Engineering,Frontend Developer,73745,2019-08-04,alyssa.rodriguez@company.com,0,1
28,EMP029,Mrs. Teresa Lutz DVM,Sales,Account Executive,81028,2020-06-22,mrs..teresa.lutz.dvm@company.com,0,1
29,EMP030,Cheryl Peterson,IT Support,System Administrator,82193,2021-03-02,cheryl.peterson@company.com,0,1
30,EMP031,Laurie Murray,IT Support,IT Technician,55281,2023-07-12,laurie.murray@company.com,0,1
31,EMP032,Sean Andrews,Finance,Financial Analyst,99933,2022-03-17,sean.andrews@company.com,0,1
32,EMP033,Anthony Sampson,Finance,Financial Analyst,76170,2023-03-18,anthony.sampson@company.com,0,1
33,EMP034,Michael Maldonado,Marketing,SEO Specialist,78888,2020-12-13,michael.maldonado@company.com,0,1
34,EMP035,John Jones,IT Support,System Administrator,73699,2022-09-06,john.jones@company.com,0,1
35,EMP036,Yesenia Klein,Marketing,Social Media Manager,77463,2021-01-02,yesenia.klein@company.com,0,1
36,EMP037,Adam Martinez,Marketing,SEO Specialist,97693,2019-11-14,adam.martinez@company.com,0,1
37,EMP038,Kendra Ward,Finance,Financial Analyst,73567,2019-08-21,kendra.ward@company.com,0,1
38,EMP039,Dennis Harris,Sales,Sales Manager,66568,2024-05-08,dennis.harris@company.com,0,1
39,EMP040,Jennifer Mendez,IT Support,IT Technician,92321,2021-10-05,jennifer.mendez@company.com,0,1
40,EMP041,Austin Rose,Marketing,Social Media Manager,83986,2020-10-26,austin.rose@company.com,0,1
41,EMP042,Grant Hunter,Human Resources,Recruiter,74028,2024-05-14,grant.hunter@company.com,0,1
42,EMP043,Kayla Hinton,Marketing,SEO Specialist,113411,2020-11-16,kayla.hinton@company.com,0,1
43,EMP044,Anna Cisneros,Engineering,DevOps Engineer,102598,2019-08-28,anna.cisneros@company.com,0,1
44,EMP045,Angela Grant,Human Resources,Recruiter,87220,2020-02-01,angela.grant@company.com,0,1
45,EMP046,Jennifer Baker,Sales,Account Executive,73902,2019-09-05,jennifer.baker@company.com,0,1
46,EMP047,Sean Fuller,Sales,Sales Associate,58420,2024-01-31,sean.fuller@company.com,0,1
47,EMP048,Stephanie Townsend,Human Resources,Recruiter,95307,2019-08-24,stephanie.townsend@company.com,0,1
48,EMP049,Grant Parker,Sales,Account Executive,55554,2019-05-23,grant.parker@company.com,0,1
49,EMP050,Susan Coleman,Marketing,Content Strategist,87292,2021-12-27,susan.coleman@company.com,0,1

In [158]:
def fy(b):
    return b*2
df['double_sal'] = df['salary'].apply(fy)

In [159]:
df

,e_id,name,department,position,salary,date_joined,email,zeros,zeros + 1,salary_sq,double_sal
0,EMP001,Gary Harper,Engineering,Frontend Developer,74889,2022-01-30,gary.harper@company.com,0,1,None,149778
1,EMP002,Lee Walsh,IT Support,System Administrator,115131,2022-01-02,lee.walsh@company.com,0,1,None,230262
2,EMP003,John Soto,Human Resources,HR Executive,107183,2019-07-08,john.soto@company.com,0,1,None,214366
3,EMP004,Jennifer Foley,Finance,Financial Analyst,116032,2024-11-21,jennifer.foley@company.com,0,1,None,232064
4,EMP005,Valerie Taylor,Marketing,Content Strategist,85420,2020-04-19,valerie.taylor@company.com,0,1,None,170840
5,EMP006,Alan Phillips,Marketing,Social Media Manager,116912,2024-11-27,alan.phillips@company.com,0,1,None,233824
6,EMP007,Ashley Henderson,Human Resources,HR Executive,85517,2023-01-05,ashley.henderson@company.com,0,1,None,171034
7,EMP008,Raymond Ellis,Finance,Financial Analyst,66548,2021-10-28,raymond.ellis@company.com,0,1,None,133096
8,EMP009,William Baker,Marketing,Content Strategist,85118,2024-05-03,william.baker@company.com,0,1,None,170236
9,EMP010,Justin James,Sales,Sales Associate,72928,2022-06-03,justin.james@company.com,0,1,None,145856
10,EMP011,Nicholas Edwards,Sales,Sales Associate,68327,2024-10-04,nicholas.edwards@company.com,0,1,None,136654
11,EMP012,Matthew Williams,IT Support,System Administrator,71895,2019-12-11,matthew.williams@company.com,0,1,None,143790
12,EMP013,Nathan Carpenter DDS,Engineering,DevOps Engineer,112869,2019-06-14,nathan.carpenter.dds@company.com,0,1,None,225738
13,EMP014,April Gonzalez,Engineering,Backend Developer,93758,2021-04-13,april.gonzalez@company.com,0,1,None,187516
14,EMP015,Cody Yoder,Sales,Sales Manager,106635,2023-01-10,cody.yoder@company.com,0,1,None,213270
15,EMP016,Jonathon Henry,Human Resources,HR Executive,117464,2022-07-13,jonathon.henry@company.com,0,1,None,234928
16,EMP017,Evelyn Bautista,Marketing,Content Strategist,77980,2022-09-17,evelyn.bautista@company.com,0,1,None,155960
17,EMP018,Matthew Pierce,Marketing,Content Strategist,106447,2024-11-30,matthew.pierce@company.com,0,1,None,212894
18,EMP019,Makayla Orozco,Sales,Sales Associate,88630,2022-09-13,makayla.orozco@company.com,0,1,None,177260
19,EMP020,Lindsay Diaz,IT Support,System Administrator,100983,2025-03-17,lindsay.diaz@company.com,0,1,None,201966
20,EMP021,Mr. Luis Williams,Engineering,Backend Developer,76696,2019-09-01,mr..luis.williams@company.com,0,1,None,153392
21,EMP022,Kevin Mclean,Marketing,Content Strategist,90045,2020-09-04,kevin.mclean@company.com,0,1,None,180090
22,EMP023,Tyler Wilson DDS,Finance,Accountant,58365,2023-06-07,tyler.wilson.dds@company.com,0,1,None,116730
23,EMP024,Shannon Smith,Finance,Financial Analyst,106443,2019-09-22,shannon.smith@company.com,0,1,None,212886
24,EMP025,Mark Gonzalez,Finance,Accountant,70423,2022-06-08,mark.gonzalez@company.com,0,1,None,140846
25,EMP026,Daniel Lewis,Marketing,Social Media Manager,100234,2022-01-25,daniel.lewis@company.com,0,1,None,200468
26,EMP027,Stephanie Rose,Marketing,SEO Specialist,72039,2024-09-18,stephanie.rose@company.com,0,1,None,144078
27,EMP028,Alyssa Rodriguez,Engineering,Frontend Developer,73745,2019-08-04,alyssa.rodriguez@company.com,0,1,None,147490
28,EMP029,Mrs. Teresa Lutz DVM,Sales,Account Executive,81028,2020-06-22,mrs..teresa.lutz.dvm@company.com,0,1,None,162056
29,EMP030,Cheryl Peterson,IT Support,System Administrator,82193,2021-03-02,cheryl.peterson@company.com,0,1,None,164386
30,EMP031,Laurie Murray,IT Support,IT Technician,55281,2023-07-12,laurie.murray@company.com,0,1,None,110562
31,EMP032,Sean Andrews,Finance,Financial Analyst,99933,2022-03-17,sean.andrews@company.com,0,1,None,199866
32,EMP033,Anthony Sampson,Finance,Financial Analyst,76170,2023-03-18,anthony.sampson@company.com,0,1,None,152340
33,EMP034,Michael Maldonado,Marketing,SEO Specialist,78888,2020-12-13,michael.maldonado@company.com,0,1,None,157776
34,EMP035,John Jones,IT Support,System Administrator,73699,2022-09-06,john.jones@company.com,0,1,None,147398
35,EMP036,Yesenia Klein,Marketing,Social Media Manager,77463,2021-01-02,yesenia.klein@company.com,0,1,None,154926
36,EMP037,Adam Martinez,Marketing,SEO Specialist,97693,2019-11-14,adam.martinez@company.com,0,1,None,195386
37,EMP038,Kendra Ward,Finance,Financial Analyst,73567,2019-08-21,kendra.ward@company.com,0,1,None,147134
38,EMP039,Dennis Harris,Sales,Sales Manager,66568,2024-05-08,dennis.harris@company.com,0,1,None,133136
39,EMP040,Jennifer Mendez,IT Support,IT Technician,92321,2021-10-05,jennifer.mendez@company.com,0,1,None,184642
40,EMP041,Austin Rose,Marketing,Social Media Manager,83986,2020-10-26,austin.rose@company.com,0,1,None,167972
41,EMP042,Grant Hunter,Human Resources,Recruiter,74028,2024-05-14,grant.hunter@company.com,0,1,None,148056
42,EMP043,Kayla Hinton,Marketing,SEO Specialist,113411,2020-11-16,kayla.hinton@company.com,0,1,None,226822
43,EMP044,Anna Cisneros,Engineering,DevOps Engineer,102598,2019-08-28,anna.cisneros@company.com,0,1,None,205196
44,EMP045,Angela Grant,Human Resources,Recruiter,87220,2020-02-01,angela.grant@company.com,0,1,None,174440
45,EMP046,Jennifer Baker,Sales,Account Executive,73902,2019-09-05,jennifer.baker@company.com,0,1,None,147804
46,EMP047,Sean Fuller,Sales,Sales Associate,58420,2024-01-31,sean.fuller@company.com,0,1,None,116840
47,EMP048,Stephanie Townsend,Human Resources,Recruiter,95307,2019-08-24,stephanie.townsend@company.com,0,1,None,190614
48,EMP049,Grant Parker,Sales,Account Executive,55554,2019-05-23,grant.parker@company.com,0,1,None,111108
49,EMP050,Susan Coleman,Marketing,Content Strategist,87292,2021-12-27,susan.coleman@company.com,0,1,None,174584

In [160]:
df.to_csv('modified.csv', index=False)

# ___________________________________________

In [164]:
dfalpha = pd.DataFrame({
    'name' : ['mojez','zehra','huma'],
    'marks' : [100,95,99],
})
dfalpha

    name  marks
0  mojez    100
1  zehra     95
2   huma     99

In [167]:
dfbeta = pd.DataFrame({
    'name' : ['mojez','huma'],
    'roll' :[1244,1255],
})
dfbeta

    name  roll
0  mojez  1244
1   huma  1255

In [169]:
pd.merge(dfalpha,dfbeta ,on='name')

    name  marks  roll
0  mojez    100  1244
1   huma     99  1255

In [170]:
pd.concat([dfalpha,dfbeta])

    name  marks    roll
0  mojez  100.0     NaN
1  zehra   95.0     NaN
2   huma   99.0     NaN
0  mojez    NaN  1244.0
1   huma    NaN  1255.0